### ISSUE TITLE
Improve dark mode for HTML content

### ISSUE THREAD

**Issue by rgpublic** [thunderbird/thunderbird-android#4198]
### Expected behavior
I'd like to see a background-color

### Actual behavior
I don't see a background-color

### Steps to reproduce
1. Send a HTML-mail with `<h1 style="background-color:red">HELLO</h1>`
2. Receive the mail with K9 in dark mode
3. Don't see no color :-(

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This is sort of by design. The CSS rules that are applied for dark mode are:

```css
* { background: black ! important; color: #F3F3F3 !important }
:link, :link * { color: #CCFF33 !important }
:visited, :visited * { color: #551A8B !important }
```

I guess we could change it to only apply the background to the `body` element. Of course this has the downside of not overriding background colors that don't work well with the new text color and/or body background color. In your example it would work out okay. But that's not generally the case.
